print ("""""WWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWW
WWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWW
WWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWW
WWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWW
WWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWW
WWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWW
WWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWW
WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW
WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW
MMMMMMMMMMMMMMMMMMMMMMMMMNOOKKKkxxxk0XKKX0kxxxkKKKOONMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMW0k::;..,o::::,....,::::o,..;::k0WMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNkc'o...,;;;d;;;........;;;d;;;,...o'ckNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNk:...l;;;;'..c,...;:;..;:;...,l..';;;:l...:kNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMXc;;;;:Ko;;;;;;x;;;;;;:kk:;;;;;;x;;;;;;oK:;;;;cNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNl....:dc.....l'.....c;:c.....'l.....cd:....lNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXl...c;cc...'l....c;..;c....l'...cc;c...lXMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNx;.l,.cc..l'..c;....;c..'l..cc.'l.;kWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWk:o'..c:,l.:;......;:.o,:c..'o:kWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMXkd'..'ckl:........:lkc'..,dxXMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMM0dc'..'d..........d'..'cdKMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMKdc..'l........l'..cdKMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0d:.,c......c,.:d0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0d:;c....c;:d0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdd:..:ddKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKO;:OKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW
WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM""""")

print ("""""
 ____  ____  ____  ____    ____  ____  ____  ____ 
( ___)(  _ \( ___)( ___)  ( ___)(_  _)(  _ \( ___)
 )__)  )   / )__)  )__)    )__)  _)(_  )   / )__) 
(__)  (_)\_)(____)(____)  (__)  (____)(_)\_)(____)
""""")
print ("""""
 ____  ____  __  __  _____  _  _  ____     _   _    __    ___  _  _ 
(  _ \(_  _)(  \/  )(  _  )( \( )(  _ \   ( )_( )  /__\  / __)( )/ )
 )(_) )_)(_  )    (  )(_)(  )  (  )(_) )   ) _ (  /(__)\( (__  )  ( 
(____/(____)(_/\/\_)(_____)(_)\_)(____/   (_) (_)(__)(__)\___)(_)\_)
""""")